// 获取文章列表
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

// 获取单条文章
export const FETCH_ONE_ARTICLE_REQUEST = 'FETCH_ONE_ARTICLE_REQUEST';
export const FETCH_ONE_ARTICLE_SUCCESS = 'FETCH_ONE_ARTICLE_SUCCESS';
export const FETCH_ONE_ARTICLE_ERROR = 'FETCH_ONE_ARTICLE_ERROR';

// 添加文章
export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';

// 修改文章
export const EDIT_ARTICLE_REQUEST = 'EDIT_ARTICLE_REQUEST';
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const EDIT_ARTICLE_ERROR = 'EDIT_ARTICLE_ERROR';

// 删除文章
export const REMOVE_ARTICLE_REQUEST = 'REMOVE_ARTICLE_REQUEST';
export const REMOVE_ARTICLE_SUCCESS = 'REMOVE_ARTICLE_SUCCESS';
export const REMOVE_ARTICLE_ERROR = 'REMOVE_ARTICLE_ERROR';

export const CLEAR_ARTICLES = 'CLEAR_ARTICLES';
