// 获取标签列表
export const FETCH_BESTWISHS_REQUEST = "FETCH_BESTWISHS_REQUEST";
export const FETCH_BESTWISHS_SUCCESS = "FETCH_BESTWISHS_SUCCESS";
export const FETCH_BESTWISHS_ERROR = "FETCH_BESTWISHS_ERROR";

// 获取单条标签
export const FETCH_ONE_BESTWISH_REQUEST = "FETCH_ONE_BESTWISH_REQUEST";
export const FETCH_ONE_BESTWISH_SUCCESS = "FETCH_ONE_BESTWISH_SUCCESS";
export const FETCH_ONE_BESTWISH_ERROR = "FETCH_ONE_BESTWISH_ERROR";

// 添加标签
export const CREATE_BESTWISH_REQUEST = "CREATE_BESTWISH_REQUEST";
export const CREATE_BESTWISH_SUCCESS = "CREATE_BESTWISH_SUCCESS";
export const CREATE_BESTWISH_ERROR = "CREATE_BESTWISH_ERROR";

// 修改标签
export const EDIT_BESTWISH_REQUEST = "EDIT_BESTWISH_REQUEST";
export const EDIT_BESTWISH_SUCCESS = "EDIT_BESTWISH_SUCCESS";
export const EDIT_BESTWISH_ERROR = "EDIT_BESTWISH_ERROR";

// 删除标签
export const REMOVE_BESTWISH_REQUEST = "REMOVE_BESTWISH_REQUEST";
export const REMOVE_BESTWISH_SUCCESS = "REMOVE_BESTWISH_SUCCESS";
export const REMOVE_BESTWISH_ERROR = "REMOVE_BESTWISH_ERROR";
