// 获取列表
export const FETCH_DEMOS_REQUEST = 'FETCH_DEMOS_REQUEST';
export const FETCH_DEMOS_SUCCESS = 'FETCH_DEMOS_SUCCESS';
export const FETCH_DEMOS_ERROR = 'FETCH_DEMOS_ERROR';

// 添加
export const CREATE_DEMO_REQUEST = 'CREATE_DEMO_REQUEST';
export const CREATE_DEMO_SUCCESS = 'CREATE_DEMO_SUCCESS';
export const CREATE_DEMO_ERROR = 'CREATE_DEMO_ERROR';

// 修改
export const EDIT_DEMO_REQUEST = 'EDIT_DEMO_REQUEST';
export const EDIT_DEMO_SUCCESS = 'EDIT_DEMO_SUCCESS';
export const EDIT_DEMO_ERROR = 'EDIT_DEMO_ERROR';

// 删除
export const REMOVE_DEMO_REQUEST = 'REMOVE_DEMO_REQUEST';
export const REMOVE_DEMO_SUCCESS = 'REMOVE_DEMO_SUCCESS';
export const REMOVE_DEMO_ERROR = 'REMOVE_DEMO_ERROR';
