// 获取标签列表
export const FETCH_MEDIAS_REQUEST = "FETCH_MEDIAS_REQUEST";
export const FETCH_MEDIAS_SUCCESS = "FETCH_MEDIAS_SUCCESS";
export const FETCH_MEDIAS_ERROR = "FETCH_MEDIAS_ERROR";

// 获取单条标签
export const FETCH_ONE_MEDIA_REQUEST = "FETCH_ONE_MEDIA_REQUEST";
export const FETCH_ONE_MEDIA_SUCCESS = "FETCH_ONE_MEDIA_SUCCESS";
export const FETCH_ONE_MEDIA_ERROR = "FETCH_ONE_MEDIA_ERROR";

// 添加标签
export const CREATE_MEDIA_REQUEST = "CREATE_MEDIA_REQUEST";
export const CREATE_MEDIA_SUCCESS = "CREATE_MEDIA_SUCCESS";
export const CREATE_MEDIA_ERROR = "CREATE_MEDIA_ERROR";

// 修改标签
export const EDIT_MEDIA_REQUEST = "EDIT_MEDIA_REQUEST";
export const EDIT_MEDIA_SUCCESS = "EDIT_MEDIA_SUCCESS";
export const EDIT_MEDIA_ERROR = "EDIT_MEDIA_ERROR";

// 删除标签
export const REMOVE_MEDIA_REQUEST = "REMOVE_MEDIA_REQUEST";
export const REMOVE_MEDIA_SUCCESS = "REMOVE_MEDIA_SUCCESS";
export const REMOVE_MEDIA_ERROR = "REMOVE_MEDIA_ERROR";
