// 获取标签列表
export const FETCH_TAGS_REQUEST = 'FETCH_TAGS_REQUEST';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_ERROR = 'FETCH_TAGS_ERROR';

// 获取单条标签
export const FETCH_ONE_TAG_REQUEST = 'FETCH_ONE_TAG_REQUEST';
export const FETCH_ONE_TAG_SUCCESS = 'FETCH_ONE_TAG_SUCCESS';
export const FETCH_ONE_TAG_ERROR = 'FETCH_ONE_TAG_ERROR';

// 添加标签
export const CREATE_TAG_REQUEST = 'CREATE_TAG_REQUEST';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_ERROR = 'CREATE_TAG_ERROR';

// 修改标签
export const EDIT_TAG_REQUEST = 'EDIT_TAG_REQUEST';
export const EDIT_TAG_SUCCESS = 'EDIT_TAG_SUCCESS';
export const EDIT_TAG_ERROR = 'EDIT_TAG_ERROR';

// 删除标签
export const REMOVE_TAG_REQUEST = 'REMOVE_TAG_REQUEST';
export const REMOVE_TAG_SUCCESS = 'REMOVE_TAG_SUCCESS';
export const REMOVE_TAG_ERROR = 'REMOVE_TAG_ERROR';
